repos:
- repo: local
  hooks:
  - id: check-ast
    name: check-ast
    entry: check-ast
    language: python
    types: [python]
  - id: check-builtin-literals
    name: check-builtin-literals
    entry: check-builtin-literals
    language: python
    types: [python]
  - id: check-case-conflict
    name: check-case-conflict
    entry: check-case-conflict
    language: python
    types: [python]
  - id: check-merge-conflict
    name: check-merge-conflict
    entry: check-merge-conflict
    language: python
    types: [text]
  - id: fix-byte-order-marker
    name: fix-byte-order-marker
    entry: fix-byte-order-marker
    language: python
    types: [python]
  - id: mixed-line-ending
    name: mixed-line-ending
    entry: mixed-line-ending
    language: python
    types_or: [c, c++, python]
  - id: end-of-file-fixer
    name: end-of-file-fixer
    entry: end-of-file-fixer
    language: python
    types_or: [c, c++, python]
  - id: trailing-whitespace-fixer
    name: trailing-whitespace-fixer
    entry: trailing-whitespace-fixer
    language: python
    types_or: [c, c++, python]
  - id: flake8
    name: flake8
    entry: flake8
    language: python
    types: [python]
  - id: black
    name: black
    entry: black
    language: python
    types: [python]
