DRIVER = "Kvaser"
KV_CHANNEL = 0
KV_ACCEPT_VIRTUAL = true
KV_BAUDRATE_PRESET = true
CAN_ID_MASTER = 257
CAN_ID_SLAVE = 258
CAN_ID_BROADCAST = 256
MAX_DLC_REQUIRED = false
BAUDRATE = 250000.0
BTL_CYCLES = 16
SAMPLE_RATE = 1
SAMPLE_POINT = 87.5
SJW = 2
TSEG1 = 5
TSEG2 = 2
CREATE_DAQ_TIMESTAMPS = false
