# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-u/using-python-with-github-actions

name: Build wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest, windows-latest] # macos-latest
    steps:
    - uses: actions/checkout@v2
    #- name: Set up Python ${{ matrix.python }}
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: ${{ matrix.python }}
    #- name: Set up QEMU
    #    if: ${{ matrix.archs == 'aarch64' }}
    #    uses: docker/setup-qemu-action@v1
    - name: Build wheel
      uses: pypa/cibuildwheel@v2.3.1
    - name: Upload to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER_NAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      if: env.TWINE_USERNAME != null
      run: |
        twine upload dist/*
    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl
